# Generated by Django 3.2.19 on 2023-07-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='icon',
            field=models.ImageField(upload_to='images'),
        ),
    ]
