# Generated by Django 4.0.6 on 2022-11-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='last name'),
        ),
    ]
