# Generated by Django 3.2.19 on 2023-06-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='box_dimensions',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
