# Generated by Django 3.2.19 on 2023-07-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_alter_inquiry_box_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
