# Generated by Django 3.2.19 on 2023-07-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_inquiry_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
